version: '3.12'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
    volumes:
      - .:/code

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db



  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - '6379:6379'

#  celery_worker:
#    build: .
#    command: celery -A app.celery_app worker --loglevel=info
#    volumes:
#      - .:/code
#    depends_on:
#      - redis
#    environment:
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run arq app.arq_worker.WorkerSettings
    container_name: arq_worker
    depends_on:
      - redis
    env_file:
      - .env
